#%RAML 1.0
title: student-raml
baseUri: http://ittrainer.in/api
protocols:
  - HTTP
  - HTTPS
version: 0.2
mediaType: 
- application/json
description: This student raml service. Updating the service to next version.

/student:
  get:
    description: This is get method for student raml service
    queryParameters: 
     format :
       type: string
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              properties:
                sno: integer
                sname:
                 type: string
                 required: false
                 example:
                  value: mayank
                m1?: integer
                m2: 
                 type: integer
                 example:
                  value: 100
                m3:
                 type: integer
                 example:
                   value: 400
               
                     
                
            example:
                value: [{
                  m1: 99,
                  m2: 88,
                  sname: "mayank",
                  sno: 100,
                  m3: 400
                }]  


  post:
    description: This is the post method for our student service to    create the students data
    

  /{studentid}:
    get:
     queryParameters: 
      format :
       type: string
     responses:
      200:
        body:
          application/json:
            type: object
            properties:
                sno: integer
                sname:
                 type: string
                 required: false
                 example:
                  value: mayank
                m1?: integer
                m2: 
                 type: integer
                 example:
                  value: 100
                m3:
                 type: integer
                 example:
                   value: 400
            example:
              value: 
                {
                 m1: 100, 
                 m2: 200, 
                 m3: 300,
                 sname: "mayank",
                 sno: 101
                }
             

    post:
      

    

  